name: Release - MacOS

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

permissions:
    contents: write

jobs:

  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: | 
        cargo build --verbose --release
    - name: Rename binary
      run: | 
        mv target/release/spotify-dl target/release/spotify-dl.macos-x86_64
    - name: Upload MacOS Artifact
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        makeLatest: True
        omitBody: True
        omitBodyDuringUpdate: True
        omitNameDuringUpdate: True
        artifacts: target/release/spotify-dl.macos-x86_64
        token: ${{ secrets.GITHUB_TOKEN }}