name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - platform: macos-latest
            target: macos-x86_64
          - platform: ubuntu-latest
            target: linux-x86_64
          - platform: windows-latest
            target: windows-x86_64
        # platform: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
    - if: matrix.platform == 'ubuntu-latest'
      run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev gcc alsa
    - name: Build
      run: | 
        cargo build --verbose --release
    - if: matrix.platform == 'windows-latest'
      name: Rename binary
      run: | 
        mv target/release/spotify-dl.exe target/release/spotify-dl.${{ matrix.target }}
    - if: matrix.platform != 'windows-latest'
      name: Rename binary
      run: | 
        mv target/release/spotify-dl target/release/spotify-dl.${{ matrix.target }}
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Build"
        files: |
          LICENSE
          target/release/spotify-dl*
