name: Release - Windows

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:

  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: | 
        cargo build --verbose --release
    - name: Rename binary
      run: | 
        mv target/release/spotify-dl.exe target/release/spotify-dl.windows-x86_64
    - name: Upload Windows Artifact
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        makeLatest: True
        omitBody: True
        omitBodyDuringUpdate: True
        omitNameDuringUpdate: True
        artifacts: target/release/spotify-dl.windows-x86_64
        token: ${{ secrets.GITHUB_TOKEN }}
